@startuml
class Todolistapplication{
+start()
+main()
}
class FXMLController{

-add_date:string
-add_description:string
-add_task:string
-add_title:string
-delete_list
-dropdown_list
-edit_date
-edit_task
-edit_title
-file_options
-open_saved
-remove
-save_button
-show_all
-show_completed:boolean
-show_incompleted:boolean
-view_list:string array


+add_to_list()
+remove_from_list()
+edit_date()
+edit_title()
+edit_description()
+save_file()
+save()
+display_specific_list()
+show_all()
+display_completed()
+load_data()
+load_help_window()
}

class Newtodo{
-Localdate date
-String description
-BooleanProperty status
--
+getdescription(String description)
+setdescription()
+getDate(Localdate date)
+setdate()
+getstatus()
+setStatus(Boolean status))
}
 FXMLController<-Newtodo
 FXMLController<-helpwindowController
 Todolistapplication<-FXMLController


 class helpwindowController{
     -TextArea textbox
     -Button adding_a_task
     -Button deleting_an_item
     -Button editing_a_task
     -Button filter_a_list
     -Button saving_and_loading
     +addingatask()
     +deletinganitem()
     +editingatask()
     +filteringalist()
     +savingandloading()
 }
@enduml