@startuml

class Todolistapplication{

-add_date:string
-add_description:string
-add_task:string
-add_title:string
-delete_list
-dropdown_list
-edit_date
-edit_task
-edit_title
-file_options
-open_saved
-remove
-save_button
-show_all
-show_completed:boolean
-show_incompleted:boolean
-view_list:string array


+add_to_list()
+remove_from_list()
+edit_date()
+edit_title()
+edit_description()
+save_file()
+display_specific_list()
+mark_complete_incomplete()
+load_data()
+setStatus(Boolean status)
}

class Newtodo{
-Localdate date()
-String description()
-Boolean status()
--
+getdescription(String description)
+getDate(Localdate date)
+setStatus(Boolean status))
}
 Todolistapplication<-Newtodo
@enduml